name: Angular_DockerImage_V2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  angular_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: |
          npm run build -- --output-path=docs

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Download and run the Docker base image
        run: docker run -d --name http_admin_mycv httpd

      - name: Copy Angular build to Docker container
        run: docker cp docs/. http_admin_mycv:/usr/local/apache2/htdocs

      - name: Commit Docker container to image
        run: |
          docker commit --change "ENV MODEL_NAME http_admin_mycv" http_admin_mycv \
          ${{ secrets.DOCKER_USER }}/admin_mycv:${{ github.sha }}

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/admin_mycv:${{ github.sha }}
